/* Generat de tools/import-board.mjs — nu edita manual.
   Geometria exactă a plansei din Figma. */

const BOARD = {
 "width": 4229,
 "height": 2391,
 "scale": 2,
 "elements": [
  {
   "id": "56:9",
   "name": "Stanesk",
   "type": "RECTANGLE",
   "x": 1499,
   "y": 14,
   "w": 370,
   "h": 392,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/stanesk.png"
  },
  {
   "id": "56:34",
   "name": "“Stuful din Delta Dunării” (2023, rețeaua PSD Olt se extinde la nivel național)",
   "type": "TEXT",
   "x": 3320,
   "y": 111,
   "w": 890,
   "h": 124,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/stuful-din-delta-dunarii-2023-reteaua-psd-ol.svg",
   "text": "“Stuful din Delta Dunării”\n(2023, rețeaua PSD Olt se extinde la nivel național)"
  },
  {
   "id": "56:50",
   "name": "Împreună cu",
   "type": "TEXT",
   "x": 2681,
   "y": 135,
   "w": 119,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/impreuna-cu.svg",
   "text": "Împreună cu"
  },
  {
   "id": "56:127",
   "name": "PSD WHITE 9",
   "type": "RECTANGLE",
   "x": 1787,
   "y": 142,
   "w": 264,
   "h": 264,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/psd-white-9.png"
  },
  {
   "id": "56:150",
   "name": "Vector 74",
   "type": "VECTOR",
   "x": 2066,
   "y": 173,
   "w": 1937,
   "h": 0,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-74.svg"
  },
  {
   "id": "56:151",
   "name": "Vector 75",
   "type": "VECTOR",
   "x": 3306,
   "y": 173,
   "w": 175,
   "h": 146,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-75.svg"
  },
  {
   "id": "56:135",
   "name": "ANIF Min. Agriculturii",
   "type": "TEXT",
   "x": 2894,
   "y": 187,
   "w": 386,
   "h": 98,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/anif-min-agriculturii.svg",
   "text": "ANIF\nMin. Agriculturii"
  },
  {
   "id": "56:132",
   "name": "Busi 2",
   "type": "RECTANGLE",
   "x": 2984,
   "y": 267,
   "w": 236,
   "h": 263,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/busi-2.png"
  },
  {
   "id": "56:33",
   "name": "Companie PRIVATĂ",
   "type": "TEXT",
   "x": 3580,
   "y": 296,
   "w": 239,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/companie-privata-6.svg",
   "text": "Companie PRIVATĂ"
  },
  {
   "id": "56:5",
   "name": "Mariana",
   "type": "RECTANGLE",
   "x": 617,
   "y": 299,
   "w": 226,
   "h": 215,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/mariana.png"
  },
  {
   "id": "56:134",
   "name": "PSD WHITE 8",
   "type": "RECTANGLE",
   "x": 3146,
   "y": 339,
   "w": 185,
   "h": 185,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/psd-white-8.png"
  },
  {
   "id": "56:133",
   "name": "CARMIN WHITE 2",
   "type": "RECTANGLE",
   "x": 3619,
   "y": 347,
   "w": 161,
   "h": 170,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/carmin-white-2.png"
  },
  {
   "id": "56:64",
   "name": "acordă proiecte către",
   "type": "TEXT",
   "x": 3372,
   "y": 378,
   "w": 202,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-catre.svg",
   "text": "acordă proiecte către"
  },
  {
   "id": "56:91",
   "name": "Paul STĂNESCU",
   "type": "TEXT",
   "x": 1404,
   "y": 401,
   "w": 559,
   "h": 144,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/paul-stanescu.svg",
   "text": "Paul STĂNESCU"
  },
  {
   "id": "56:47",
   "name": "propulsează funcția Secretar de Stat în Ministerul Justiției lui",
   "type": "TEXT",
   "x": 924,
   "y": 413,
   "w": 570,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/propulseaza-functia-secretar-de-stat-in-mini.svg",
   "text": "propulsează funcția Secretar de Stat în Ministerul Justiției lui"
  },
  {
   "id": "56:48",
   "name": "l-a instalat pe",
   "type": "TEXT",
   "x": 2779,
   "y": 413,
   "w": 132,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/l-a-instalat-pe.svg",
   "text": "l-a instalat pe"
  },
  {
   "id": "56:108",
   "name": "Vector 45",
   "type": "VECTOR",
   "x": 3349,
   "y": 416,
   "w": 261,
   "h": 0,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-45.svg"
  },
  {
   "id": "56:121",
   "name": "Vector 58",
   "type": "VECTOR",
   "x": 843,
   "y": 451,
   "w": 645,
   "h": 100,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-58.svg"
  },
  {
   "id": "56:115",
   "name": "Vector 53",
   "type": "VECTOR",
   "x": 1877,
   "y": 451,
   "w": 1055.5,
   "h": 0,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-53.svg"
  },
  {
   "id": "56:109",
   "name": "Vector 78",
   "type": "VECTOR",
   "x": 3341,
   "y": 457,
   "w": 261,
   "h": 0,
   "rotation": 180,
   "opacity": 1,
   "file": "assets/board/vector-78.svg"
  },
  {
   "id": "56:65",
   "name": "este firma de casă a lui",
   "type": "TEXT",
   "x": 3367,
   "y": 457,
   "w": 221,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/este-firma-de-casa-a-lui.svg",
   "text": "este firma de casă a lui"
  },
  {
   "id": "56:123",
   "name": "SRI WHITE 4",
   "type": "RECTANGLE",
   "x": 372,
   "y": 474,
   "w": 201,
   "h": 201,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/sri-white-4.png"
  },
  {
   "id": "56:92",
   "name": "Vector 36",
   "type": "VECTOR",
   "x": 1264.75,
   "y": 492,
   "w": 430,
   "h": 95,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-36.svg"
  },
  {
   "id": "56:51",
   "name": "este Mentorul Politic al lui",
   "type": "TEXT",
   "x": 1349,
   "y": 503,
   "w": 244,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/este-mentorul-politic-al-lui.svg",
   "text": "este Mentorul Politic al lui"
  },
  {
   "id": "56:12",
   "name": "Mariana MOȚ",
   "type": "TEXT",
   "x": 618,
   "y": 514,
   "w": 223,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/mariana-mot.svg",
   "text": "Mariana MOȚ"
  },
  {
   "id": "56:21",
   "name": "Spitalul JUDEȚEAN Slatina",
   "type": "TEXT",
   "x": 2588,
   "y": 517,
   "w": 323,
   "h": 198,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/spitalul-judetean-slatina.svg",
   "text": "Spitalul\nJUDEȚEAN Slatina"
  },
  {
   "id": "56:43",
   "name": "Florin ‘Busi’ Barbu",
   "type": "TEXT",
   "x": 2937,
   "y": 523,
   "w": 329,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/florin-busi-barbu.svg",
   "text": "Florin ‘Busi’ Barbu"
  },
  {
   "id": "56:55",
   "name": "controlează",
   "type": "TEXT",
   "x": 2108,
   "y": 578,
   "w": 108,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/controleaza-2.svg",
   "text": "controlează"
  },
  {
   "id": "56:35",
   "name": "Președinte CJ OLT",
   "type": "TEXT",
   "x": 974,
   "y": 584,
   "w": 594,
   "h": 110,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/presedinte-cj-olt.svg",
   "text": "Președinte CJ OLT"
  },
  {
   "id": "56:119",
   "name": "Vector 56",
   "type": "VECTOR",
   "x": 730,
   "y": 601,
   "w": 0,
   "h": 210,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-56.svg"
  },
  {
   "id": "56:98",
   "name": "Vector 70",
   "type": "VECTOR",
   "x": 2690,
   "y": 607,
   "w": 396,
   "h": 990,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/vector-70.svg"
  },
  {
   "id": "56:99",
   "name": "Vector 71",
   "type": "VECTOR",
   "x": 2911,
   "y": 607,
   "w": 175,
   "h": 1681,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/vector-71.svg"
  },
  {
   "id": "56:116",
   "name": "Vector 81",
   "type": "VECTOR",
   "x": 1578,
   "y": 616,
   "w": 999.5,
   "h": 0,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-81.svg"
  },
  {
   "id": "56:56",
   "name": "scapă de acuzare de ucidere prin",
   "type": "TEXT",
   "x": 2007,
   "y": 616,
   "w": 311,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/scapa-de-acuzare-de-ucidere-prin.svg",
   "text": "scapă de acuzare de ucidere prin"
  },
  {
   "id": "56:52",
   "name": "este Mama lui",
   "type": "TEXT",
   "x": 685,
   "y": 633,
   "w": 38,
   "h": 133,
   "rotation": 90,
   "opacity": 1,
   "file": "assets/board/este-mama-lui.svg",
   "text": "este Mama lui"
  },
  {
   "id": "56:7",
   "name": "Opresk",
   "type": "RECTANGLE",
   "x": 1081,
   "y": 644,
   "w": 396,
   "h": 382,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/opresk.png"
  },
  {
   "id": "56:3",
   "name": "Coldea",
   "type": "RECTANGLE",
   "x": 395,
   "y": 684,
   "w": 156,
   "h": 164,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/coldea.png"
  },
  {
   "id": "56:8",
   "name": "Pandarof",
   "type": "RECTANGLE",
   "x": 76,
   "y": 715,
   "w": 166,
   "h": 288,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/pandarof.png"
  },
  {
   "id": "56:96",
   "name": "Vector 82",
   "type": "VECTOR",
   "x": 2750,
   "y": 718.25,
   "w": 81,
   "h": 620,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/vector-82.svg"
  },
  {
   "id": "56:77",
   "name": "este firma de casă a lui",
   "type": "TEXT",
   "x": 1986,
   "y": 720,
   "w": 221,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/este-firma-de-casa-a-lui-2.svg",
   "text": "este firma de casă a lui"
  },
  {
   "id": "56:126",
   "name": "PSD WHITE 5",
   "type": "RECTANGLE",
   "x": 1376,
   "y": 750,
   "w": 264,
   "h": 264,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/psd-white-5.png"
  },
  {
   "id": "56:103",
   "name": "Vector 73",
   "type": "VECTOR",
   "x": 1632,
   "y": 758,
   "w": 893,
   "h": 472,
   "rotation": 180,
   "opacity": 1,
   "file": "assets/board/vector-73.svg"
  },
  {
   "id": "56:53",
   "name": "este Nașul lui",
   "type": "TEXT",
   "x": 909,
   "y": 801,
   "w": 128,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/este-nasul-lui.svg",
   "text": "este Nașul lui"
  },
  {
   "id": "56:36",
   "name": "Primar SLATINA",
   "type": "TEXT",
   "x": 628,
   "y": 803,
   "w": 192,
   "h": 98,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/primar-slatina.svg",
   "text": "Primar\nSLATINA"
  },
  {
   "id": "56:83",
   "name": "este Cumnatul lui",
   "type": "TEXT",
   "x": 1821,
   "y": 803,
   "w": 165,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/este-cumnatul-lui.svg",
   "text": "este Cumnatul lui"
  },
  {
   "id": "56:20",
   "name": "Primar PIATRA-OLT",
   "type": "TEXT",
   "x": 2138,
   "y": 803,
   "w": 267,
   "h": 98,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/primar-piatra-olt.svg",
   "text": "Primar\nPIATRA-OLT"
  },
  {
   "id": "56:154",
   "name": "Peace sign 1",
   "type": "RECTANGLE",
   "x": 2852,
   "y": 803,
   "w": 1414.65,
   "h": 1851.49,
   "rotation": 13.91,
   "opacity": 0.02,
   "file": "assets/board/peace-sign-1.png"
  },
  {
   "id": "56:94",
   "name": "Vector 38",
   "type": "VECTOR",
   "x": 1654.5,
   "y": 841,
   "w": 474,
   "h": 0,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-38.svg"
  },
  {
   "id": "56:93",
   "name": "Vector 37",
   "type": "VECTOR",
   "x": 839,
   "y": 842,
   "w": 275,
   "h": 0,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-37.svg"
  },
  {
   "id": "56:15",
   "name": "Florian COLDEA",
   "type": "TEXT",
   "x": 387,
   "y": 852,
   "w": 170,
   "h": 41,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/florian-coldea.svg",
   "text": "Florian COLDEA"
  },
  {
   "id": "56:95",
   "name": "Vector 79",
   "type": "VECTOR",
   "x": 1654.5,
   "y": 876,
   "w": 474,
   "h": 0,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-79.svg"
  },
  {
   "id": "56:84",
   "name": "alocă fonduri suplimentare primăriei lui",
   "type": "TEXT",
   "x": 1720,
   "y": 876,
   "w": 370,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/aloca-fonduri-suplimentare-primariei-lui.svg",
   "text": "alocă fonduri suplimentare primăriei lui"
  },
  {
   "id": "56:112",
   "name": "Vector 50",
   "type": "VECTOR",
   "x": 312,
   "y": 877,
   "w": 60,
   "h": 158,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-50.svg"
  },
  {
   "id": "56:85",
   "name": "o sprijină pe",
   "type": "TEXT",
   "x": 334,
   "y": 893,
   "w": 38,
   "h": 115,
   "rotation": 90,
   "opacity": 1,
   "file": "assets/board/o-sprijina-pe.svg",
   "text": "o sprijină pe"
  },
  {
   "id": "56:6",
   "name": "Mot",
   "type": "RECTANGLE",
   "x": 636,
   "y": 899,
   "w": 201,
   "h": 238,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/mot.png"
  },
  {
   "id": "56:144",
   "name": "Nicusor Rada 2",
   "type": "RECTANGLE",
   "x": 2147,
   "y": 899,
   "w": 209,
   "h": 227,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/nicusor-rada-2.png"
  },
  {
   "id": "56:106",
   "name": "Vector 43",
   "type": "VECTOR",
   "x": 2075,
   "y": 914,
   "w": 125,
   "h": 331,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/vector-43.svg"
  },
  {
   "id": "56:128",
   "name": "PSD WHITE 7",
   "type": "RECTANGLE",
   "x": 788,
   "y": 926,
   "w": 185,
   "h": 185,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/psd-white-7.png"
  },
  {
   "id": "56:72",
   "name": "emite ilegal autorizatii pentru",
   "type": "TEXT",
   "x": 2040,
   "y": 938,
   "w": 42,
   "h": 274,
   "rotation": 90,
   "opacity": 1,
   "file": "assets/board/emite-ilegal-autorizatii-pentru.svg",
   "text": "emite ilegal autorizatii pentru"
  },
  {
   "id": "80:2",
   "name": "PSD WHITE 10",
   "type": "RECTANGLE",
   "x": 2311,
   "y": 938,
   "w": 188,
   "h": 188,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/psd-white-10.png"
  },
  {
   "id": "56:71",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 2788,
   "y": 938,
   "w": 38,
   "h": 176,
   "rotation": 90,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-9.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:78",
   "name": "este firma de casă a lui",
   "type": "TEXT",
   "x": 1709,
   "y": 945,
   "w": 224,
   "h": 29,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/este-firma-de-casa-a-lui-3.svg",
   "text": "este firma de casă a lui"
  },
  {
   "id": "56:147",
   "name": "Vector 66",
   "type": "VECTOR",
   "x": 1646.5,
   "y": 981,
   "w": 339,
   "h": 258,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-66.svg"
  },
  {
   "id": "56:13",
   "name": "Marina PANDAROF",
   "type": "TEXT",
   "x": 6,
   "y": 998,
   "w": 304,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/marina-pandarof.svg",
   "text": "Marina PANDAROF"
  },
  {
   "id": "56:45",
   "name": "Marius OPRESCU",
   "type": "TEXT",
   "x": 1024,
   "y": 1011,
   "w": 492,
   "h": 110,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/marius-oprescu.svg",
   "text": "Marius OPRESCU"
  },
  {
   "id": "56:61",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 3035,
   "y": 1030,
   "w": 35,
   "h": 176,
   "rotation": 90,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-4.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:105",
   "name": "Vector 42",
   "type": "VECTOR",
   "x": 1465,
   "y": 1061,
   "w": 51,
   "h": 318,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-42.svg"
  },
  {
   "id": "56:113",
   "name": "Vector 51",
   "type": "VECTOR",
   "x": 185,
   "y": 1069,
   "w": 461,
   "h": 101,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-51.svg"
  },
  {
   "id": "56:118",
   "name": "Vector 55",
   "type": "VECTOR",
   "x": 185,
   "y": 1069,
   "w": 101,
   "h": 629,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-55.svg"
  },
  {
   "id": "56:87",
   "name": "îl aprivizionează cu droguri pe",
   "type": "TEXT",
   "x": 245,
   "y": 1072,
   "w": 283,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/il-aprivizioneaza-cu-droguri-pe-2.svg",
   "text": " îl aprivizionează cu droguri pe"
  },
  {
   "id": "56:104",
   "name": "Vector 40",
   "type": "VECTOR",
   "x": 1288.75,
   "y": 1095,
   "w": 0,
   "h": 426,
   "rotation": 180,
   "opacity": 1,
   "file": "assets/board/vector-40.svg"
  },
  {
   "id": "56:44",
   "name": "Nicușor RADA",
   "type": "TEXT",
   "x": 2147,
   "y": 1118,
   "w": 233,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/nicusor-rada.svg",
   "text": "Nicușor RADA"
  },
  {
   "id": "56:111",
   "name": "Vector 49",
   "type": "VECTOR",
   "x": 920.75,
   "y": 1128,
   "w": 368,
   "h": 713,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-49.svg"
  },
  {
   "id": "56:39",
   "name": "Emil MOȚ",
   "type": "TEXT",
   "x": 656,
   "y": 1130,
   "w": 154,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/emil-mot.svg",
   "text": "Emil MOȚ"
  },
  {
   "id": "56:110",
   "name": "Vector 48",
   "type": "VECTOR",
   "x": 877.75,
   "y": 1135,
   "w": 383,
   "h": 715,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-48.svg"
  },
  {
   "id": "56:80",
   "name": "achită comisionul de “10%”",
   "type": "TEXT",
   "x": 958,
   "y": 1142,
   "w": 257,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/achita-comisionul-de-10.svg",
   "text": "achită comisionul de “10%”"
  },
  {
   "id": "56:114",
   "name": "Vector 52",
   "type": "VECTOR",
   "x": 733,
   "y": 1187,
   "w": 46,
   "h": 502,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-52.svg"
  },
  {
   "id": "56:57",
   "name": "acordă proiecte direct lui",
   "type": "TEXT",
   "x": 963,
   "y": 1207,
   "w": 236,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-direct-lui.svg",
   "text": "acordă proiecte direct lui"
  },
  {
   "id": "56:54",
   "name": "controlează",
   "type": "TEXT",
   "x": 1516,
   "y": 1230,
   "w": 38,
   "h": 108,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/controleaza.svg",
   "text": "controlează"
  },
  {
   "id": "56:30",
   "name": "Companie PRIVATĂ",
   "type": "TEXT",
   "x": 1899,
   "y": 1245,
   "w": 239,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/companie-privata-3.svg",
   "text": "Companie PRIVATĂ"
  },
  {
   "id": "56:28",
   "name": "Companie PRIVATĂ",
   "type": "TEXT",
   "x": 2397,
   "y": 1245,
   "w": 239,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/companie-privata.svg",
   "text": "Companie PRIVATĂ"
  },
  {
   "id": "56:86",
   "name": "îl aprivizionează cu droguri pe",
   "type": "TEXT",
   "x": 150,
   "y": 1256,
   "w": 34,
   "h": 283,
   "rotation": 90,
   "opacity": 1,
   "file": "assets/board/il-aprivizioneaza-cu-droguri-pe.svg",
   "text": " îl aprivizionează cu droguri pe"
  },
  {
   "id": "56:27",
   "name": "Director",
   "type": "TEXT",
   "x": 374,
   "y": 1290,
   "w": 106,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/director-3.svg",
   "text": "Director"
  },
  {
   "id": "56:26",
   "name": "Director",
   "type": "TEXT",
   "x": 846,
   "y": 1293,
   "w": 106,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/director-2.svg",
   "text": "Director"
  },
  {
   "id": "56:143",
   "name": "MineralportWhite 2",
   "type": "RECTANGLE",
   "x": 1763,
   "y": 1297,
   "w": 491,
   "h": 82,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/mineralportwhite-2.png"
  },
  {
   "id": "56:129",
   "name": "Wagramer 2",
   "type": "RECTANGLE",
   "x": 2299,
   "y": 1304,
   "w": 432.09,
   "h": 68,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/wagramer-2.png"
  },
  {
   "id": "56:37",
   "name": "C.A.O.",
   "type": "TEXT",
   "x": 365,
   "y": 1346,
   "w": 139,
   "h": 49,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/c-a-o.svg",
   "text": "C.A.O."
  },
  {
   "id": "56:38",
   "name": "C.A.O.",
   "type": "TEXT",
   "x": 835,
   "y": 1349,
   "w": 139,
   "h": 49,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/c-a-o-2.svg",
   "text": "C.A.O."
  },
  {
   "id": "56:90",
   "name": "este Socrul lui",
   "type": "TEXT",
   "x": 695,
   "y": 1369,
   "w": 38,
   "h": 134,
   "rotation": 90,
   "opacity": 1,
   "file": "assets/board/este-socrul-lui.svg",
   "text": "este Socrul lui"
  },
  {
   "id": "56:152",
   "name": "Postolache 2",
   "type": "RECTANGLE",
   "x": 1873,
   "y": 1376,
   "w": 247,
   "h": 247,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/postolache-2.png"
  },
  {
   "id": "56:25",
   "name": "Companie de STAT",
   "type": "TEXT",
   "x": 1390,
   "y": 1384,
   "w": 234,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/companie-de-stat-2.svg",
   "text": "Companie de STAT"
  },
  {
   "id": "56:153",
   "name": "Titiriga",
   "type": "RECTANGLE",
   "x": 2420,
   "y": 1386,
   "w": 253,
   "h": 243,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/titiriga.png"
  },
  {
   "id": "56:4",
   "name": "Covaciu",
   "type": "RECTANGLE",
   "x": 790,
   "y": 1389,
   "w": 336,
   "h": 265,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/covaciu.png"
  },
  {
   "id": "56:10",
   "name": "Usurelu",
   "type": "RECTANGLE",
   "x": 326,
   "y": 1393,
   "w": 223,
   "h": 264,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/usurelu.png"
  },
  {
   "id": "56:125",
   "name": "SRI WHITE 6",
   "type": "RECTANGLE",
   "x": 953,
   "y": 1395,
   "w": 191,
   "h": 191,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/sri-white-6.png"
  },
  {
   "id": "56:81",
   "name": "achită comisionul de “10%”",
   "type": "TEXT",
   "x": 1289,
   "y": 1421,
   "w": 38,
   "h": 257,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/achita-comisionul-de-10-2.svg",
   "text": "achită comisionul de “10%”"
  },
  {
   "id": "56:131",
   "name": "Olt Drum SA WHITE 2",
   "type": "RECTANGLE",
   "x": 1352,
   "y": 1439,
   "w": 311,
   "h": 32,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/olt-drum-sa-white-2.png"
  },
  {
   "id": "80:4",
   "name": "PSD WHITE 11",
   "type": "RECTANGLE",
   "x": 486,
   "y": 1466,
   "w": 188,
   "h": 188,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/psd-white-11.png"
  },
  {
   "id": "56:101",
   "name": "Vector 77",
   "type": "VECTOR",
   "x": 1539.75,
   "y": 1482,
   "w": 299,
   "h": 132,
   "rotation": -180,
   "opacity": 1,
   "file": "assets/board/vector-77.svg"
  },
  {
   "id": "56:146",
   "name": "Vector 65",
   "type": "VECTOR",
   "x": 1502.25,
   "y": 1490,
   "w": 214,
   "h": 457,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-65.svg"
  },
  {
   "id": "56:100",
   "name": "Vector 67",
   "type": "VECTOR",
   "x": 1578.75,
   "y": 1490,
   "w": 269,
   "h": 59,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-67.svg"
  },
  {
   "id": "56:70",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 1616,
   "y": 1510,
   "w": 176,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-8.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:62",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 2779,
   "y": 1559,
   "w": 176,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-5.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:73",
   "name": "vinde asfalt și balast către",
   "type": "TEXT",
   "x": 1579,
   "y": 1579,
   "w": 250,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vinde-asfalt-si-balast-catre.svg",
   "text": "vinde asfalt și balast către"
  },
  {
   "id": "56:137",
   "name": "Claudiu POSTOLACHE",
   "type": "TEXT",
   "x": 1862,
   "y": 1623,
   "w": 345,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/claudiu-postolache.svg",
   "text": "Claudiu POSTOLACHE"
  },
  {
   "id": "56:40",
   "name": "VALERIU ȚIȚIRIGĂ",
   "type": "TEXT",
   "x": 2410,
   "y": 1623,
   "w": 273,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/valeriu-titiriga.svg",
   "text": "VALERIU ȚIȚIRIGĂ"
  },
  {
   "id": "56:68",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 1502,
   "y": 1650,
   "w": 38,
   "h": 176,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-7.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:82",
   "name": "susține pe",
   "type": "TEXT",
   "x": 1111,
   "y": 1651,
   "w": 98,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/sustine-pe.svg",
   "text": "susține pe"
  },
  {
   "id": "56:102",
   "name": "Vector 39",
   "type": "VECTOR",
   "x": 1678,
   "y": 1656,
   "w": 171,
   "h": 258,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-39.svg"
  },
  {
   "id": "56:69",
   "name": "face plăți lui",
   "type": "TEXT",
   "x": 1704,
   "y": 1656,
   "w": 116,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/face-plati-lui.svg",
   "text": "face plăți lui"
  },
  {
   "id": "56:97",
   "name": "Vector 72",
   "type": "VECTOR",
   "x": 2696,
   "y": 1656,
   "w": 290,
   "h": 291,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-72.svg"
  },
  {
   "id": "56:76",
   "name": "fostul șofer al tatălui lui",
   "type": "TEXT",
   "x": 2731,
   "y": 1656,
   "w": 224,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/fostul-sofer-al-tatalui-lui.svg",
   "text": "fostul șofer al tatălui lui"
  },
  {
   "id": "56:14",
   "name": "Cătălin UȘURELU",
   "type": "TEXT",
   "x": 301,
   "y": 1658,
   "w": 279,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/catalin-usurelu.svg",
   "text": "Cătălin UȘURELU"
  },
  {
   "id": "56:16",
   "name": "Vasile COVACIU",
   "type": "TEXT",
   "x": 806,
   "y": 1660,
   "w": 257,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vasile-covaciu.svg",
   "text": "Vasile COVACIU"
  },
  {
   "id": "56:107",
   "name": "Vector 44",
   "type": "VECTOR",
   "x": 1076.25,
   "y": 1689,
   "w": 184,
   "h": 61,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-44.svg"
  },
  {
   "id": "56:142",
   "name": "Vector 69",
   "type": "VECTOR",
   "x": 1242,
   "y": 1696,
   "w": 1340,
   "h": 677,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/vector-69.svg"
  },
  {
   "id": "56:149",
   "name": "Vector 76",
   "type": "VECTOR",
   "x": 1921,
   "y": 1696,
   "w": 548,
   "h": 145,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-76.svg"
  },
  {
   "id": "56:148",
   "name": "Vector 68",
   "type": "VECTOR",
   "x": 2143,
   "y": 1696,
   "w": 378,
   "h": 145,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-68.svg"
  },
  {
   "id": "56:79",
   "name": "face plăți circulare cu",
   "type": "TEXT",
   "x": 2129,
   "y": 1715,
   "w": 205,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/face-plati-circulare-cu.svg",
   "text": "face plăți circulare cu"
  },
  {
   "id": "56:117",
   "name": "Vector 54",
   "type": "VECTOR",
   "x": 456.75,
   "y": 1735,
   "w": 482,
   "h": 46,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-54.svg"
  },
  {
   "id": "56:88",
   "name": "este Director la",
   "type": "TEXT",
   "x": 504,
   "y": 1743,
   "w": 145,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/este-director-la.svg",
   "text": "este Director la"
  },
  {
   "id": "56:89",
   "name": "este Director la",
   "type": "TEXT",
   "x": 737,
   "y": 1743,
   "w": 145,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/este-director-la-2.svg",
   "text": "este Director la"
  },
  {
   "id": "56:120",
   "name": "Vector 57",
   "type": "VECTOR",
   "x": 698,
   "y": 1782,
   "w": 0,
   "h": 76,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-57.svg"
  },
  {
   "id": "56:60",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 2261,
   "y": 1791,
   "w": 176,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-3.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:32",
   "name": "Companie PRIVATĂ",
   "type": "TEXT",
   "x": 1110,
   "y": 1850,
   "w": 315,
   "h": 55,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/companie-privata-5.svg",
   "text": "Companie PRIVATĂ"
  },
  {
   "id": "56:31",
   "name": "Companie PRIVATĂ",
   "type": "TEXT",
   "x": 1704,
   "y": 1850,
   "w": 315,
   "h": 55,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/companie-privata-4.svg",
   "text": "Companie PRIVATĂ"
  },
  {
   "id": "56:24",
   "name": "Director",
   "type": "TEXT",
   "x": 2094,
   "y": 1850,
   "w": 106,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/director.svg",
   "text": "Director"
  },
  {
   "id": "56:29",
   "name": "Companie PRIVATĂ",
   "type": "TEXT",
   "x": 2623,
   "y": 1850,
   "w": 239,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/companie-privata-2.svg",
   "text": "Companie PRIVATĂ"
  },
  {
   "id": "56:23",
   "name": "Companie de STAT",
   "type": "TEXT",
   "x": 580,
   "y": 1859,
   "w": 234,
   "h": 47,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/companie-de-stat.svg",
   "text": "Companie de STAT"
  },
  {
   "id": "56:74",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 2355,
   "y": 1859,
   "w": 176,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-10.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:122",
   "name": "CAO WHITE 2",
   "type": "RECTANGLE",
   "x": 343,
   "y": 1889,
   "w": 709,
   "h": 108,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/cao-white-2.png"
  },
  {
   "id": "56:18",
   "name": "S.G.A. OLT",
   "type": "TEXT",
   "x": 1943,
   "y": 1900,
   "w": 412,
   "h": 78,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/s-g-a-olt.svg",
   "text": "S.G.A.\nOLT"
  },
  {
   "id": "56:19",
   "name": "Condor PĂDURARU",
   "type": "TEXT",
   "x": 2582,
   "y": 1900,
   "w": 312,
   "h": 122,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/condor-paduraru.svg",
   "text": "Condor\nPĂDURARU"
  },
  {
   "id": "56:22",
   "name": "OLD&NEW CONSTRUCT",
   "type": "TEXT",
   "x": 1090,
   "y": 1914,
   "w": 357,
   "h": 122,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/old-new-construct.svg",
   "text": "OLD&NEW\nCONSTRUCT"
  },
  {
   "id": "56:17",
   "name": "PANADRIA",
   "type": "TEXT",
   "x": 1665,
   "y": 1921,
   "w": 412,
   "h": 78,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/panadria.svg",
   "text": "PANADRIA"
  },
  {
   "id": "56:130",
   "name": "Adrian Barbu - Panadria 2",
   "type": "RECTANGLE",
   "x": 1848,
   "y": 1946,
   "w": 384,
   "h": 301,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/adrian-barbu-panadria-2.png"
  },
  {
   "id": "56:138",
   "name": "Paduraru 2",
   "type": "RECTANGLE",
   "x": 2581,
   "y": 1982,
   "w": 354,
   "h": 275,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/paduraru-2.png"
  },
  {
   "id": "56:157",
   "name": "Vector 83",
   "type": "VECTOR",
   "x": 698,
   "y": 1984,
   "w": 576,
   "h": 389,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/vector-83.svg"
  },
  {
   "id": "56:145",
   "name": "Pisicu 2",
   "type": "RECTANGLE",
   "x": 1023,
   "y": 2013,
   "w": 370,
   "h": 248,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/pisicu-2.png"
  },
  {
   "id": "56:66",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 3044,
   "y": 2015,
   "w": 35,
   "h": 176,
   "rotation": 90,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-6.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:42",
   "name": "Mircea ‘Pisicu’ Ungureanu",
   "type": "TEXT",
   "x": 1033,
   "y": 2256,
   "w": 469,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/mircea-pisicu-ungureanu.svg",
   "text": "Mircea ‘Pisicu’ Ungureanu"
  },
  {
   "id": "56:41",
   "name": "Adrian BARBU",
   "type": "TEXT",
   "x": 1894,
   "y": 2256,
   "w": 292,
   "h": 77,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/adrian-barbu.svg",
   "text": "Adrian BARBU"
  },
  {
   "id": "56:136",
   "name": "Sorin PĂDURARU",
   "type": "TEXT",
   "x": 2622,
   "y": 2256,
   "w": 276,
   "h": 62,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/sorin-paduraru.svg",
   "text": "Sorin PĂDURARU"
  },
  {
   "id": "57:160",
   "name": "Vector 84",
   "type": "VECTOR",
   "x": 1105,
   "y": 2310,
   "w": 938,
   "h": 63,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/vector-84.svg"
  },
  {
   "id": "56:141",
   "name": "Vector 64",
   "type": "VECTOR",
   "x": 1814,
   "y": 2310,
   "w": 938,
   "h": 63,
   "rotation": -90,
   "opacity": 1,
   "file": "assets/board/vector-64.svg"
  },
  {
   "id": "56:58",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 945,
   "y": 2335,
   "w": 176,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:59",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 1521,
   "y": 2335,
   "w": 176,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-2.svg",
   "text": "acordă proiecte lui"
  },
  {
   "id": "56:75",
   "name": "acordă proiecte lui",
   "type": "TEXT",
   "x": 2507,
   "y": 2335,
   "w": 176,
   "h": 38,
   "rotation": 0,
   "opacity": 1,
   "file": "assets/board/acorda-proiecte-lui-11.svg",
   "text": "acordă proiecte lui"
  }
 ]
};
